BInt.register_test("cheats/add_money", function(t)
	t:start_run({ seed = "JOKER123" })
	local before = t:get_money()
	t:add_money(100)
	local after = t:get_money()
	t:assert_eq(after, before + 100, "should have gained $100")
	t:log("money: $" .. before .. " -> $" .. after)
end)

BInt.register_test("cheats/set_money", function(t)
	t:start_run({ seed = "JOKER123" })
	t:set_money(999)
	t:assert_eq(t:get_money(), 999, "money should be $999")
end)

BInt.register_test("cheats/set_hands", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:set_hands(99)
	local info = t:get_round_info()
	t:assert_eq(info.hands_left, 99, "should have 99 hands")
end)

BInt.register_test("cheats/set_discards", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:set_discards(99)
	local info = t:get_round_info()
	t:assert_eq(info.discards_left, 99, "should have 99 discards")
end)

BInt.register_test("cheats/set_reroll_cost", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	t:set_reroll_cost(0)
	t:assert_eq(t:get_reroll_cost(), 0, "reroll cost should be $0")
	t:set_money(0)
	t:reroll():assert()
	t:assert_eq(t:get_money(), 0, "should still have $0 after free reroll")
	t:log("set_reroll_cost works")
end)

BInt.register_test("cheats/set_reroll_cost_custom", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	t:set_reroll_cost(42)
	t:assert_eq(t:get_reroll_cost(), 42, "reroll cost should be $42")
end)

BInt.register_test("cheats/spawn_joker", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	t:spawn_joker("j_joker"):assert()
	local jokers = t:get_jokers()
	t:assert_eq(#jokers, 1, "should have 1 joker")
	t:assert_eq(jokers[1].key, "j_joker", "should be Joker")
	t:log("spawned " .. jokers[1].key)
end)

BInt.register_test("cheats/spawn_consumable", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	t:spawn_consumable("c_fool"):assert()
	local consumables = t:get_consumables()
	t:assert_eq(#consumables, 1, "should have 1 consumable")
	t:assert_eq(consumables[1].key, "c_fool", "should be The Fool")
	t:log("spawned " .. consumables[1].key)
end)

BInt.register_test("cheats/spawn_multiple_jokers", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	t:spawn_joker("j_joker"):assert()
	t:spawn_joker("j_greedy_joker"):assert()
	t:spawn_joker("j_lusty_joker"):assert()

	local jokers = t:get_jokers()
	t:assert_eq(#jokers, 3, "should have 3 jokers")
	t:assert_eq(jokers[1].key, "j_joker")
	t:assert_eq(jokers[2].key, "j_greedy_joker")
	t:assert_eq(jokers[3].key, "j_lusty_joker")
end)

BInt.register_test("cheats/spawn_voucher", function(t)
	t:start_run({ seed = "JOKER123" })
	t:spawn_voucher("v_grabber"):assert()
	t:assert_contains(t:get_owned_vouchers(), "v_grabber", "voucher should be owned")
	t:log("spawn_voucher works")
end)

BInt.register_test("cheats/add_playing_card", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	local full_before = #t:get_full_deck()
	t:add_playing_card("As"):assert()
	local full_after = #t:get_full_deck()
	t:assert_eq(full_after, full_before + 1, "should have one more card")
	t:log("add_playing_card works")
end)

BInt.register_test("cheats/remove_playing_card", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:add_playing_card("As"):assert()
	local before = #t:get_full_deck()
	t:remove_playing_card("As"):assert()
	local after = #t:get_full_deck()
	t:assert_eq(after, before - 1, "should have one fewer card")
	t:log("remove_playing_card works")
end)

BInt.register_test("cheats/set_joker_edition", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:spawn_joker("j_joker"):assert()
	t:set_joker_edition(1, "foil"):assert()
	local jokers = t:get_jokers()
	t:assert_true(jokers[1].edition ~= nil, "joker should have an edition")
	t:log("set_joker_edition works")
end)

BInt.register_test("cheats/set_enhancement", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	local hand = t:get_hand()
	t:assert_true(#hand > 0, "need cards in hand")
	t:set_enhancement(1, "m_gold"):assert()
	hand = t:get_hand()
	t:assert_eq(hand[1].enhancement, "m_gold", "card should have gold enhancement")
	t:log("set_enhancement works")
end)

BInt.register_test("cheats/set_seal", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:set_seal(1, "Gold"):assert()
	local hand = t:get_hand()
	t:assert_eq(hand[1].seal, "Gold", "card should have Gold seal")
	t:log("set_seal works")
end)

BInt.register_test("cheats/unlock_all", function(t)
	t:start_run({ seed = "JOKER123" })
	t:unlock_all()
	t:assert_true(G.P_CENTERS["j_joker"].unlocked, "Joker should be unlocked")
	t:assert_true(G.P_CENTERS["j_joker"].discovered, "Joker should be discovered")
	t:log("unlock_all works")
end)
