BInt.register_test("queries/get_money", function(t)
	t:start_run({ seed = "JOKER123" })
	local money = t:get_money()
	t:assert_true(type(money) == "number", "money should be a number")
	t:log("starting money: $" .. money)
end)

BInt.register_test("queries/get_hand", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	local hand = t:get_hand()
	t:assert_true(#hand > 0, "should have cards in hand")

	local card = hand[1]
	t:assert_true(card.rank ~= nil, "card should have rank")
	t:assert_true(card.suit ~= nil, "card should have suit")
	t:assert_true(card.id ~= nil, "card should have id")
	t:log("hand has " .. #hand .. " cards, first: " .. card.id)
end)

BInt.register_test("queries/get_jokers_empty", function(t)
	t:start_run({ seed = "JOKER123" })
	local jokers = t:get_jokers()
	t:assert_eq(#jokers, 0, "should start with no jokers")
end)

BInt.register_test("queries/get_round_info", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	local info = t:get_round_info()
	t:assert_true(info.ante ~= nil, "should have ante")
	t:assert_true(info.hands_left ~= nil, "should have hands_left")
	t:assert_true(info.discards_left ~= nil, "should have discards_left")
	t:log("ante: " .. info.ante .. ", hands: " .. info.hands_left .. ", discards: " .. info.discards_left)
end)

BInt.register_test("queries/get_deck", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	local deck = t:get_deck()
	t:assert_true(#deck > 0, "deck should have cards")
	t:log("deck has " .. #deck .. " cards")
end)

BInt.register_test("queries/get_full_deck", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	local full = t:get_full_deck()
	t:assert_true(#full >= 52, "full deck should have at least 52 cards")

	local areas_seen = {}
	for _, card in ipairs(full) do
		areas_seen[card.area] = true
	end
	t:assert_true(areas_seen["hand"], "should have cards in hand area")
	t:assert_true(areas_seen["deck"], "should have cards in deck area")
	t:log("full deck: " .. #full .. " cards across areas")
end)

BInt.register_test("queries/get_state_name", function(t)
	t:start_run({ seed = "JOKER123" })
	local name = t:get_state_name()
	t:assert_eq(name, "BLIND_SELECT", "should be BLIND_SELECT after start_run")
	t:log("state name: " .. name)
end)

BInt.register_test("queries/get_score_during_round", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	local score = t:get_score()
	t:assert_true(score.blind_chips ~= nil, "should have blind_chips")
	t:assert_true(score.scored_chips ~= nil, "should have scored_chips")
	t:log("blind requires " .. tostring(score.blind_chips) .. " chips")
end)

BInt.register_test("queries/get_consumables", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:assert_eq(#t:get_consumables(), 0, "should start with no consumables")
	t:spawn_consumable("c_fool"):assert()
	local cons = t:get_consumables()
	t:assert_eq(#cons, 1, "should have 1 consumable")
	t:assert_eq(cons[1].key, "c_fool")
	t:assert_true(cons[1].type ~= nil, "should have type")
	t:log("get_consumables works")
end)

BInt.register_test("queries/get_shop_cards", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	local cards = t:get_shop_cards()
	t:assert_true(#cards > 0, "shop should have cards")
	local card = cards[1]
	t:assert_true(card.key ~= nil, "shop card should have key")
	t:assert_true(card.cost ~= nil, "shop card should have cost")
	t:log("get_shop_cards: " .. #cards .. " cards, first: " .. card.key .. " ($" .. card.cost .. ")")
end)

BInt.register_test("queries/get_shop_vouchers", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	local vouchers = t:get_shop_vouchers()
	t:assert_true(#vouchers > 0, "shop should have vouchers")
	t:assert_true(vouchers[1].key ~= nil, "voucher should have key")
	t:log("get_shop_vouchers: " .. #vouchers .. " vouchers")
end)

BInt.register_test("queries/get_shop_packs", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	local packs = t:get_shop_packs()
	t:assert_true(#packs > 0, "shop should have packs")
	t:assert_true(packs[1].key ~= nil, "pack should have key")
	t:log("get_shop_packs: " .. #packs .. " packs")
end)

BInt.register_test("queries/get_last_hand", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()
	t:highlight({ 1, 2, 3, 4, 5 }):assert()
	t:play_hand():assert()
	local last = t:get_last_hand()
	t:assert_true(last.hand_type ~= nil, "should have hand_type")
	t:log("last hand type: " .. tostring(last.hand_type))
end)

BInt.register_test("queries/get_pack_cards", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	t:set_money(999)
	local packs = t:get_shop_packs()
	if #packs > 0 then
		t:buy_pack(1):assert()
		local pack_cards = t:get_pack_cards()
		t:assert_true(#pack_cards > 0, "pack should have cards")
		t:log("get_pack_cards: " .. #pack_cards .. " cards in pack")
		t:skip_pack():assert()
	else
		t:log("no packs available, skipping")
	end
end)

BInt.register_test("queries/get_state", function(t)
	t:start_run({ seed = "JOKER123" })
	t:assert_eq(t:get_state(), G.STATES.BLIND_SELECT, "get_state should return BLIND_SELECT")
end)

BInt.register_test("queries/get_reroll_cost", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	local cost = t:get_reroll_cost()
	t:assert_true(type(cost) == "number", "reroll cost should be a number")
	t:assert_gte(cost, 0, "reroll cost should be non-negative")
	t:log("reroll cost: $" .. cost)
end)

BInt.register_test("queries/get_reroll_cost_increases", function(t)
	t:start_run({ seed = "JOKER123" })
	t:go_to_shop():assert()
	local cost_before = t:get_reroll_cost()
	t:set_money(999)
	t:reroll():assert()
	local cost_after = t:get_reroll_cost()
	t:assert_gt(cost_after, cost_before, "reroll cost should increase after rerolling")
	t:log("reroll cost: $" .. cost_before .. " -> $" .. cost_after)
end)

BInt.register_test("queries/get_highlighted", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	local highlighted = t:get_highlighted()
	t:assert_eq(#highlighted, 0, "should start with no highlighted cards")

	t:highlight({ 1, 2, 3 }):assert()
	highlighted = t:get_highlighted()
	t:assert_eq(#highlighted, 3, "should have 3 highlighted cards")
	t:assert_true(highlighted[1].rank ~= nil, "highlighted card should have rank")
	t:assert_true(highlighted[1].suit ~= nil, "highlighted card should have suit")
	t:assert_true(highlighted[1].id ~= nil, "highlighted card should have id")
	t:log("get_highlighted: " .. #highlighted .. " cards")
end)

BInt.register_test("queries/get_highlighted_after_unhighlight", function(t)
	t:start_run({ seed = "JOKER123" })
	t:select_blind():assert()

	t:highlight({ 1, 2, 3 }):assert()
	t:assert_eq(#t:get_highlighted(), 3, "should have 3 highlighted")

	t:unhighlight_all()
	t:assert_eq(#t:get_highlighted(), 0, "should have 0 after unhighlight")
end)

BInt.register_test("queries/get_blind_on_deck", function(t)
	t:start_run({ seed = "JOKER123" })
	local blind = t:get_blind_on_deck()
	t:assert_eq(blind, "Small", "should start on Small blind")

	t:skip_blind():assert()
	blind = t:get_blind_on_deck()
	t:assert_eq(blind, "Big", "should advance to Big blind after skip")
	t:log("blind_on_deck: " .. blind)
end)

BInt.register_test("queries/get_owned_vouchers_empty", function(t)
	t:start_run({ seed = "JOKER123" })
	local vouchers = t:get_owned_vouchers()
	t:assert_eq(#vouchers, 0, "should start with no owned vouchers")
end)

BInt.register_test("queries/get_owned_vouchers_after_spawn", function(t)
	t:start_run({ seed = "JOKER123" })
	t:spawn_voucher("v_grabber"):assert()
	local vouchers = t:get_owned_vouchers()
	t:assert_eq(#vouchers, 1, "should have 1 voucher")
	t:assert_contains(vouchers, "v_grabber", "should contain v_grabber")
	t:log("owned vouchers: " .. #vouchers)
end)

BInt.register_test("queries/get_owned_vouchers_multiple", function(t)
	t:start_run({ seed = "JOKER123" })
	t:spawn_voucher("v_grabber"):assert()
	t:spawn_voucher("v_seed_money"):assert()
	local vouchers = t:get_owned_vouchers()
	t:assert_eq(#vouchers, 2, "should have 2 vouchers")
	t:assert_contains(vouchers, "v_grabber", "should contain v_grabber")
	t:assert_contains(vouchers, "v_seed_money", "should contain v_seed_money")
end)
